//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace meis007Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class meis007Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new meis007Entities object using the connection string found in the 'meis007Entities' section of the application configuration file.
        /// </summary>
        public meis007Entities() : base("name=meis007Entities", "meis007Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new meis007Entities object.
        /// </summary>
        public meis007Entities(string connectionString) : base(connectionString, "meis007Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new meis007Entities object.
        /// </summary>
        public meis007Entities(EntityConnection connection) : base(connection, "meis007Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<B2CCustomerinfo> B2CCustomerinfo
        {
            get
            {
                if ((_B2CCustomerinfo == null))
                {
                    _B2CCustomerinfo = base.CreateObjectSet<B2CCustomerinfo>("B2CCustomerinfo");
                }
                return _B2CCustomerinfo;
            }
        }
        private ObjectSet<B2CCustomerinfo> _B2CCustomerinfo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<B2CPaxinfo> B2CPaxinfo
        {
            get
            {
                if ((_B2CPaxinfo == null))
                {
                    _B2CPaxinfo = base.CreateObjectSet<B2CPaxinfo>("B2CPaxinfo");
                }
                return _B2CPaxinfo;
            }
        }
        private ObjectSet<B2CPaxinfo> _B2CPaxinfo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CityMaster> CityMasters
        {
            get
            {
                if ((_CityMasters == null))
                {
                    _CityMasters = base.CreateObjectSet<CityMaster>("CityMasters");
                }
                return _CityMasters;
            }
        }
        private ObjectSet<CityMaster> _CityMasters;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the B2CCustomerinfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToB2CCustomerinfo(B2CCustomerinfo b2CCustomerinfo)
        {
            base.AddObject("B2CCustomerinfo", b2CCustomerinfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the B2CPaxinfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToB2CPaxinfo(B2CPaxinfo b2CPaxinfo)
        {
            base.AddObject("B2CPaxinfo", b2CPaxinfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CityMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCityMasters(CityMaster cityMaster)
        {
            base.AddObject("CityMasters", cityMaster);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="meis007Model", Name="B2CCustomerinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class B2CCustomerinfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new B2CCustomerinfo object.
        /// </summary>
        /// <param name="customerSNo">Initial value of the CustomerSNo property.</param>
        public static B2CCustomerinfo CreateB2CCustomerinfo(global::System.Int64 customerSNo)
        {
            B2CCustomerinfo b2CCustomerinfo = new B2CCustomerinfo();
            b2CCustomerinfo.CustomerSNo = customerSNo;
            return b2CCustomerinfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CustomerSNo
        {
            get
            {
                return _CustomerSNo;
            }
            set
            {
                if (_CustomerSNo != value)
                {
                    OnCustomerSNoChanging(value);
                    ReportPropertyChanging("CustomerSNo");
                    _CustomerSNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerSNo");
                    OnCustomerSNoChanged();
                }
            }
        }
        private global::System.Int64 _CustomerSNo;
        partial void OnCustomerSNoChanging(global::System.Int64 value);
        partial void OnCustomerSNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                OnCustomerIDChanging(value);
                ReportPropertyChanging("CustomerID");
                _CustomerID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerID");
                OnCustomerIDChanged();
            }
        }
        private global::System.String _CustomerID;
        partial void OnCustomerIDChanging(global::System.String value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxEmail
        {
            get
            {
                return _PaxEmail;
            }
            set
            {
                OnPaxEmailChanging(value);
                ReportPropertyChanging("PaxEmail");
                _PaxEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxEmail");
                OnPaxEmailChanged();
            }
        }
        private global::System.String _PaxEmail;
        partial void OnPaxEmailChanging(global::System.String value);
        partial void OnPaxEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxFirstName
        {
            get
            {
                return _PaxFirstName;
            }
            set
            {
                OnPaxFirstNameChanging(value);
                ReportPropertyChanging("PaxFirstName");
                _PaxFirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxFirstName");
                OnPaxFirstNameChanged();
            }
        }
        private global::System.String _PaxFirstName;
        partial void OnPaxFirstNameChanging(global::System.String value);
        partial void OnPaxFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxMiddleName
        {
            get
            {
                return _PaxMiddleName;
            }
            set
            {
                OnPaxMiddleNameChanging(value);
                ReportPropertyChanging("PaxMiddleName");
                _PaxMiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxMiddleName");
                OnPaxMiddleNameChanged();
            }
        }
        private global::System.String _PaxMiddleName;
        partial void OnPaxMiddleNameChanging(global::System.String value);
        partial void OnPaxMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxLastName
        {
            get
            {
                return _PaxLastName;
            }
            set
            {
                OnPaxLastNameChanging(value);
                ReportPropertyChanging("PaxLastName");
                _PaxLastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxLastName");
                OnPaxLastNameChanged();
            }
        }
        private global::System.String _PaxLastName;
        partial void OnPaxLastNameChanging(global::System.String value);
        partial void OnPaxLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxTelNo
        {
            get
            {
                return _PaxTelNo;
            }
            set
            {
                OnPaxTelNoChanging(value);
                ReportPropertyChanging("PaxTelNo");
                _PaxTelNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxTelNo");
                OnPaxTelNoChanged();
            }
        }
        private global::System.String _PaxTelNo;
        partial void OnPaxTelNoChanging(global::System.String value);
        partial void OnPaxTelNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxmobileNo
        {
            get
            {
                return _PaxmobileNo;
            }
            set
            {
                OnPaxmobileNoChanging(value);
                ReportPropertyChanging("PaxmobileNo");
                _PaxmobileNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxmobileNo");
                OnPaxmobileNoChanged();
            }
        }
        private global::System.String _PaxmobileNo;
        partial void OnPaxmobileNoChanging(global::System.String value);
        partial void OnPaxmobileNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxCity
        {
            get
            {
                return _PaxCity;
            }
            set
            {
                OnPaxCityChanging(value);
                ReportPropertyChanging("PaxCity");
                _PaxCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxCity");
                OnPaxCityChanged();
            }
        }
        private global::System.String _PaxCity;
        partial void OnPaxCityChanging(global::System.String value);
        partial void OnPaxCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxAdd1
        {
            get
            {
                return _PaxAdd1;
            }
            set
            {
                OnPaxAdd1Changing(value);
                ReportPropertyChanging("PaxAdd1");
                _PaxAdd1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxAdd1");
                OnPaxAdd1Changed();
            }
        }
        private global::System.String _PaxAdd1;
        partial void OnPaxAdd1Changing(global::System.String value);
        partial void OnPaxAdd1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxAdd2
        {
            get
            {
                return _PaxAdd2;
            }
            set
            {
                OnPaxAdd2Changing(value);
                ReportPropertyChanging("PaxAdd2");
                _PaxAdd2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxAdd2");
                OnPaxAdd2Changed();
            }
        }
        private global::System.String _PaxAdd2;
        partial void OnPaxAdd2Changing(global::System.String value);
        partial void OnPaxAdd2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxAdd3
        {
            get
            {
                return _PaxAdd3;
            }
            set
            {
                OnPaxAdd3Changing(value);
                ReportPropertyChanging("PaxAdd3");
                _PaxAdd3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxAdd3");
                OnPaxAdd3Changed();
            }
        }
        private global::System.String _PaxAdd3;
        partial void OnPaxAdd3Changing(global::System.String value);
        partial void OnPaxAdd3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxPassword
        {
            get
            {
                return _PaxPassword;
            }
            set
            {
                OnPaxPasswordChanging(value);
                ReportPropertyChanging("PaxPassword");
                _PaxPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxPassword");
                OnPaxPasswordChanged();
            }
        }
        private global::System.String _PaxPassword;
        partial void OnPaxPasswordChanging(global::System.String value);
        partial void OnPaxPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PaxLastLogDatetime
        {
            get
            {
                return _PaxLastLogDatetime;
            }
            set
            {
                OnPaxLastLogDatetimeChanging(value);
                ReportPropertyChanging("PaxLastLogDatetime");
                _PaxLastLogDatetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaxLastLogDatetime");
                OnPaxLastLogDatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PaxLastLogDatetime;
        partial void OnPaxLastLogDatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPaxLastLogDatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String authenicationcode
        {
            get
            {
                return _authenicationcode;
            }
            set
            {
                OnauthenicationcodeChanging(value);
                ReportPropertyChanging("authenicationcode");
                _authenicationcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("authenicationcode");
                OnauthenicationcodeChanged();
            }
        }
        private global::System.String _authenicationcode;
        partial void OnauthenicationcodeChanging(global::System.String value);
        partial void OnauthenicationcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InService
        {
            get
            {
                return _InService;
            }
            set
            {
                OnInServiceChanging(value);
                ReportPropertyChanging("InService");
                _InService = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InService");
                OnInServiceChanged();
            }
        }
        private global::System.String _InService;
        partial void OnInServiceChanging(global::System.String value);
        partial void OnInServiceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="meis007Model", Name="B2CPaxinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class B2CPaxinfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new B2CPaxinfo object.
        /// </summary>
        /// <param name="customerSno">Initial value of the CustomerSno property.</param>
        public static B2CPaxinfo CreateB2CPaxinfo(global::System.Int64 customerSno)
        {
            B2CPaxinfo b2CPaxinfo = new B2CPaxinfo();
            b2CPaxinfo.CustomerSno = customerSno;
            return b2CPaxinfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CustomerSno
        {
            get
            {
                return _CustomerSno;
            }
            set
            {
                if (_CustomerSno != value)
                {
                    OnCustomerSnoChanging(value);
                    ReportPropertyChanging("CustomerSno");
                    _CustomerSno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerSno");
                    OnCustomerSnoChanged();
                }
            }
        }
        private global::System.Int64 _CustomerSno;
        partial void OnCustomerSnoChanging(global::System.Int64 value);
        partial void OnCustomerSnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                OnCustomerIdChanging(value);
                ReportPropertyChanging("CustomerId");
                _CustomerId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerId");
                OnCustomerIdChanged();
            }
        }
        private global::System.String _CustomerId;
        partial void OnCustomerIdChanging(global::System.String value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxFirstName
        {
            get
            {
                return _PaxFirstName;
            }
            set
            {
                OnPaxFirstNameChanging(value);
                ReportPropertyChanging("PaxFirstName");
                _PaxFirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxFirstName");
                OnPaxFirstNameChanged();
            }
        }
        private global::System.String _PaxFirstName;
        partial void OnPaxFirstNameChanging(global::System.String value);
        partial void OnPaxFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxMiddleName
        {
            get
            {
                return _PaxMiddleName;
            }
            set
            {
                OnPaxMiddleNameChanging(value);
                ReportPropertyChanging("PaxMiddleName");
                _PaxMiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxMiddleName");
                OnPaxMiddleNameChanged();
            }
        }
        private global::System.String _PaxMiddleName;
        partial void OnPaxMiddleNameChanging(global::System.String value);
        partial void OnPaxMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxLastName
        {
            get
            {
                return _PaxLastName;
            }
            set
            {
                OnPaxLastNameChanging(value);
                ReportPropertyChanging("PaxLastName");
                _PaxLastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxLastName");
                OnPaxLastNameChanged();
            }
        }
        private global::System.String _PaxLastName;
        partial void OnPaxLastNameChanging(global::System.String value);
        partial void OnPaxLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PaxDOB
        {
            get
            {
                return _PaxDOB;
            }
            set
            {
                OnPaxDOBChanging(value);
                ReportPropertyChanging("PaxDOB");
                _PaxDOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaxDOB");
                OnPaxDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _PaxDOB;
        partial void OnPaxDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnPaxDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nationality
        {
            get
            {
                return _Nationality;
            }
            set
            {
                OnNationalityChanging(value);
                ReportPropertyChanging("Nationality");
                _Nationality = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nationality");
                OnNationalityChanged();
            }
        }
        private global::System.String _Nationality;
        partial void OnNationalityChanging(global::System.String value);
        partial void OnNationalityChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="meis007Model", Name="CityMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CityMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CityMaster object.
        /// </summary>
        /// <param name="cityID">Initial value of the CityID property.</param>
        /// <param name="cityName">Initial value of the CityName property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="modDate">Initial value of the ModDate property.</param>
        public static CityMaster CreateCityMaster(global::System.String cityID, global::System.String cityName, global::System.String userID, global::System.DateTime modDate)
        {
            CityMaster cityMaster = new CityMaster();
            cityMaster.CityID = cityID;
            cityMaster.CityName = cityName;
            cityMaster.UserID = userID;
            cityMaster.ModDate = modDate;
            return cityMaster;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CityID
        {
            get
            {
                return _CityID;
            }
            set
            {
                if (_CityID != value)
                {
                    OnCityIDChanging(value);
                    ReportPropertyChanging("CityID");
                    _CityID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CityID");
                    OnCityIDChanged();
                }
            }
        }
        private global::System.String _CityID;
        partial void OnCityIDChanging(global::System.String value);
        partial void OnCityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CityName
        {
            get
            {
                return _CityName;
            }
            set
            {
                if (_CityName != value)
                {
                    OnCityNameChanging(value);
                    ReportPropertyChanging("CityName");
                    _CityName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CityName");
                    OnCityNameChanged();
                }
            }
        }
        private global::System.String _CityName;
        partial void OnCityNameChanging(global::System.String value);
        partial void OnCityNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CountryID
        {
            get
            {
                return _CountryID;
            }
            set
            {
                OnCountryIDChanging(value);
                ReportPropertyChanging("CountryID");
                _CountryID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CountryID");
                OnCountryIDChanged();
            }
        }
        private global::System.String _CountryID;
        partial void OnCountryIDChanging(global::System.String value);
        partial void OnCountryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModDate
        {
            get
            {
                return _ModDate;
            }
            set
            {
                if (_ModDate != value)
                {
                    OnModDateChanging(value);
                    ReportPropertyChanging("ModDate");
                    _ModDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ModDate");
                    OnModDateChanged();
                }
            }
        }
        private global::System.DateTime _ModDate;
        partial void OnModDateChanging(global::System.DateTime value);
        partial void OnModDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> H2H
        {
            get
            {
                return _H2H;
            }
            set
            {
                OnH2HChanging(value);
                ReportPropertyChanging("H2H");
                _H2H = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("H2H");
                OnH2HChanged();
            }
        }
        private Nullable<global::System.Int16> _H2H;
        partial void OnH2HChanging(Nullable<global::System.Int16> value);
        partial void OnH2HChanged();

        #endregion
    
    }

    #endregion
    
}
